# Generated by Django 4.1.3 on 2022-11-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_f"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="f",
        ),
    ]
